import { host } from "../globalRoutes";

export const Leave_Form_Submit = `${host}/otheracademic/api/leave-form-submit/`;
export const Leave_PG_Submit = `${host}/otheracademic/api/leave-pg-submit/`;
export const Bonafide_Form_Submit = `${host}/otheracademic/api/bonafide-form-submit/`;
export const Fetch_Pending_Bonafide_Request = `${host}/otheracademic/api/admin-bonafide-requests/`;
export const Update_Bonafide_Status = `${host}/otheracademic/api/admin-updates/`;
export const Get_Bonafide_Status = `${host}/otheracademic/api/bonafide-status/`;
export const Fetch_Pending_Request = `${host}/otheracademic/api/fetch-pending-leaves/`;
export const Update_Leave_Status = `${host}/otheracademic/api/update-leave-status/ `;
export const Fetch_Pending_Request_TA = `${host}/otheracademic/api/fetch-pending-leaves-ta/`;
export const Update_Leave_Status_TA = `${host}/otheracademic/api/update-leave-status-ta/`;
export const Fetch_Pending_Request_Thesis = `${host}/otheracademic/api/fetch-pending-leaves-thesis/`;
export const Update_Leave_Status_Thesis = `${host}/otheracademic/api/update-leave-status-thesis/`;
export const Get_Leave_Requests = `${host}/otheracademic/api/get-leave-requests/`;
export const Get_Leave_Request = `${host}/otheracademic/api/get_leave_requests/`;
export const Get_PG_Leave_Requests = `${host}/otheracademic/api/get-pg-leave-requests/`;
export const Assistantship_Form_Submit = `${host}/otheracademic/api/assistantship-form-submit/`;
export const DeptAdmin_Fetch_Pending_Assistantship_Requests = `${host}/otheracademic/api/deptadmin_fetch_pending_assistantship_requests/`;
export const DeptAdmin_Update_Assistantship_Status = `${host}/otheracademic/api/deptadmin_update_assistantship_status/`;
export const Hod_Fetch_Pending_Assistantship_Requests = `${host}/otheracademic/api/hod_fetch_pending_assistantship_requests/`;
export const Hod_Update_Assistantship_Status = `${host}/otheracademic/api/hod_update_assistantship_status/`;
export const AcadAdmin_Fetch_Pending_Assistantship_Requests = `${host}/otheracademic/api/acadadmin_fetch_pending_assistantship_requests/`;
export const AcadAdmin_Update_Assistantship_Status = `${host}/otheracademic/api/acadadmin_update_assistantship_status/`;
export const Get_Assistantship_Status = `${host}/otheracademic/api/get_assistantship_status/`;
